// Publish project specific data
(function() {
rh = window.rh;
model = rh.model;

rh.consts('DEFAULT_TOPIC', encodeURI("#OpMan/OpMan_RH_IT/Accensione_della_macchina_EDT-.htm".substring(1)));
rh.consts('START_FILEPATH', encodeURI('index.html'));
rh.consts('HELP_ID', '5063599E-AC59-4AFD-BF6E-E54A1BEC39B4' || 'preview');
rh.consts('LNG_STOP_WORDS', ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "abbisognare", "alcuna", "alcune", "alcuni", "alcuno", "altra", "altre", "altri", "altro", "anche", "anziché", "avere", "ciascun", "ciascuna", "ciascuno", "come", "con", "cosa", "così", "da", "dentro", "di", "dopo", "dove", "dovere", "è", "e", "entrambe", "entrambi", "entro", "eppure", "era", "erano", "eri", "ero", "essere", "essi", "esso", "fa", "fare", "fatto", "già", "ha", "il", "in", "io", "lì", "loro", "lungo", "ma", "modo", "nessuna", "nessuno", "noi", "non", "o", "ok", "okay", "ottenere", "per", "perché", "più", "potere", "potrebbe", "quale", "quando", "quella", "quelle", "quelli", "quello", "questa", "queste", "questi", "questo", "qui", "quindi", "sarà", "sarai", "sarò", "se", "senza", "sono", "stato", "stessa", "stesso", "su", "tra", "troppo", "tu", "tuo", "tutte", "tutti", "un", "una", "uno", "usando", "usare", "usato", "vedere", "voi", "volere", "vostro"]);
rh.consts('LNG_SUBSTR_SEARCH', 0);

model.publish(rh.consts('KEY_DIR'), "ltr");
model.publish(rh.consts('KEY_LNG'), {"Reset":"Reimposta","SearchResultsPerScreen":"Risultati ricerca per pagina","SyncToc":"SyncToc","HomeButton":"Home page","WebSearchButton":"WebSearch","ApplyTip":"Applica","HighlightSearchResults":"Evidenzia risultati ricerca","GlossaryFilterTerms":"Trova termine","WebSearch":"WebSearch","Show":"Mostra","EnableAndSearch":"Mostra i risultati che includono tutte le parole cercate","ShowAll":"Mostra tutto","Next":">>","Print":"Stampa","NoScriptErrorMsg":"Per vedere questa pagina, attivare il supporto JavaScript nel browser.","PreviousLabel":"Precedente","Hide":"Nascondi","Search":"Cerca","Contents":"Argomenti","ShowHide":"Mostra/Nascondi","Canceled":"Annullato","EndOfResults":"Fine dei risultati della ricerca.","Loading":"Caricamento in corso...","SidebarToggleTip":"Espandi/comprimi","ContentFilterChanged":"Il filtro del contenuto è cambiato, cerca di nuovo","Logo":"Logo","Logo/Author":"Prodotto da","JS_alert_LoadXmlFailed":"Errore: Impossibile caricare il file XML.","SearchTitle":"Cerca","Searching":"Ricerca in corso...","Disabled Next":">>","Cancel":"Annulla","JS_alert_InitDatabaseFailed":"Errore: Impossibile inizializzare il database.","ResultsFoundText":"Trovato/i %1 risultato/i per %2","UnknownError":"Errore sconosciuto","Seperate":"|","Index":"Indice analitico","TopicsNotFound":"Non è stato trovato nessun argomento.","SearchPageTitle":"Risultati ricerca","Glossary":"Glossario","Filter":"Filtra","HideAll":"Nascondi tutto","TableOfContents":"Sommario","NextLabel":"Successivo","Disabled Prev":"<<","Back":"Indietro","SearchOptions":"Opzioni di ricerca","OpenLinkInNewTab":"Apri in una nuova scheda","Prev":"<<","ToTopTip":"Torna all’inizio","NavTip":"Menu","IeCompatibilityErrorMsg":"Questa pagina non è visualizzabile in Explorer 8 e versioni precedenti.","IndexFilterKewords":"Trova parola chiave","JS_alert_InvalidExpression_1":"Il testo digitato non è un'espressione valida."});
})();